### ISSUE TITLE
Possible Security Vulnerabilities

### ISSUE THREAD

**Issue by ventolinmono** [DBinaghi/plugin-LimitVisibilityToOwn#1]
Hi, thanks for the plugin.

Just wanted to point out that it does not restrict access to elements by typing the correct URL but only hides links from users on the graphical interface. Guessing the correct URL is easy because items are numbered.

There is also a problem when using this plugin with Collection Tree plugin because it shows all collections regardless which collection was created by any user.

I think this is important to point out because it could be understood that the plugin could be used for protecting confidential documents on the archive from other users but it acts more like a filter.

Thanks again for the plugin.

**Comment by DBinaghi** [comment]
Hi.
Thanks for your comments.

The plugin is not supposed to make it impossible for a user to see Items (s)he did not contribute, but just to make it easier for users to see the list of their contributed Items (Omeka itself make it not possible for them to edit Items they have not the right to edit, anyway). So, it's not really a "security" issue. This said, if you come up with a solution that can be implemented in the plugin, I'd be glad to consider it.

I do not have Collection Tree plugin installed, so cannot really check the other issue at the moment; hopefully I'll be able to do it in the near future. Again, if you come up with a solution, just do a pull request and I'll be glad to consider it.

Cheers.

**Comment by DBinaghi** [comment]
Tried it with CollectionTree plugin, and as I said there is "security vulnerability", as rights to edit an Item or Collection are assigned and checked by Omeka itself. It's true CollectionTree does not apply the restrictions set by this particular plugin, but that would happen with any plugin using its own way to list Collections or Items.
